"""PEN-12 report-only Monte Carlo: marginal-edge + mined-noise calibration.

Part A reproduces the review's marginal-edge experiment after M1:
  * for seed k in range(seeds), rng = np.random.default_rng(510_000 + k)
  * T=1000 daily bars from 2021-01-01
  * net[t] ~ Normal(IC * SD, SD), IC=0.05, SD=0.01
  * score through P7/P8 with a fresh temp ledger and no holdout
  * report structural-kill rate and overall kill rate

Part B reproduces the M2 mined-noise attack:
  * for seed k in range(seeds), rng = np.random.default_rng(620_000 + k)
  * generate K=500 zero-edge T=1000 daily series, net_j[t] ~ Normal(0, 0.01)
  * select the highest full-window Sharpe series
  * submit only that winner as one external paper claim, hiding the private search
  * declare the mined window as the claim sample_period and attach post_sample with
    data_end == sample_end, so post_years == 0.0
  * report research-supported, clean-watch, and any-watch rates

ENFORCING (PEN-12): exits 1 if a true marginal edge structurally kills above 20% (kill above
25%), or best-of-K mined noise reaches a survivor verdict (research-supported > 0%,
clean-watch > 10%, or any-watch > 10%). The any-watch rate is the deflation-guarding metric;
supported and clean-watch remain enforced for downstream survivor caps. The declared config
floor is frozen; a breach means fix the gate, not the floor.

Run:
    .venv/bin/python scripts/calibration_power_mining.py [seeds]
"""
from __future__ import annotations

import os
import sys
import tempfile
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

os.environ["PENROSE_HOLDOUT_LOCK"] = os.path.join(
    tempfile.gettempdir(), "penrose_calib_power_mining_holdout.lock"
)

from penrose import config  # noqa: E402

config.COST_PROVENANCE = "measured"

from penrose.brain import Claim  # noqa: E402
from penrose.pipeline import p7_backtest as P7  # noqa: E402
from penrose.pipeline import stages  # noqa: E402


STRUCTURAL_KILLS = {
    "in_sample_only",
    "regime_fragile",
    "walk_forward_drift",
    "no_signal_alignment",
}


def _claim() -> Claim:
    return Claim(
        claim_id="pen12-marginal-edge",
        statement="synthetic marginal edge calibration claim",
        mechanism="calibration",
        scope="daily synthetic returns",
        horizon="daily",
        source_id="pen12",
        source_span="Monte Carlo generated by scripts/calibration_power_mining.py",
        claimed_metric_quote="IC=0.05",
        applicable_strategy_class="powercal",
    )


def _mined_claim(idx: pd.DatetimeIndex) -> Claim:
    return Claim(
        claim_id="pen12-mined-noise",
        statement="synthetic mined-noise calibration claim",
        mechanism="calibration",
        scope="daily synthetic returns",
        horizon="daily",
        source_id="pen12",
        source_span="Monte Carlo generated by scripts/calibration_power_mining.py",
        claimed_metric_quote="best of hidden K=500 zero-edge series",
        applicable_strategy_class="mined_noise",
        sample_period={"start": str(idx[0].date()), "end": str(idx[-1].date())},
    )


def _score_marginal_edge(seed_index: int) -> tuple[str, str | None, dict]:
    rng = np.random.default_rng(510_000 + seed_index)
    t = 1000
    ic = 0.05
    sd = 0.01
    idx = pd.date_range("2021-01-01", periods=t, freq="D")
    net = pd.Series(rng.normal(ic * sd, sd, t), index=idx)
    positions = pd.Series(1.0, index=idx)

    old_ledger = P7.LEDGER
    with tempfile.TemporaryDirectory(prefix="penrose-pen12-a-") as tmp:
        P7.LEDGER = Path(tmp) / "backtest_ledger.tsv"
        try:
            bt = P7.run_backtest(
                f"medge{seed_index}",
                net,
                positions,
                252.0,
                family="powercal::x",
                log=False,
            )
            decision = stages.p8_verdict(_claim(), bt, {}, False)
            return decision.verdict, decision.kill_reason, decision.metrics
        finally:
            P7.LEDGER = old_ledger


def _score_mined_noise(seed_index: int) -> tuple[str, str | None, dict]:
    rng = np.random.default_rng(620_000 + seed_index)
    t = 1000
    k = 500
    sd = 0.01
    idx = pd.date_range("2021-01-01", periods=t, freq="D")
    candidates = rng.normal(0.0, sd, (k, t))
    means = candidates.mean(axis=1)
    vols = candidates.std(axis=1, ddof=1)
    sharpes = np.divide(means, vols, out=np.full(k, -np.inf), where=vols > 0)
    winner = candidates[int(np.argmax(sharpes))]
    net = pd.Series(winner, index=idx)
    positions = pd.Series(1.0, index=idx)
    claim = _mined_claim(idx)

    old_ledger = P7.LEDGER
    with tempfile.TemporaryDirectory(prefix="penrose-pen12-b-") as tmp:
        P7.LEDGER = Path(tmp) / "backtest_ledger.tsv"
        try:
            bt = P7.run_backtest(
                f"mined{seed_index}",
                net,
                positions,
                252.0,
                family="mined::x",
                generation_source="paper",
                search_denominator=None,
                log=False,
            )
            sample_end = claim.sample_period["end"]
            bt["post_sample"] = {
                "sample_end": sample_end,
                "data_end": str(idx[-1].date()),
                "post_years": 0.0,
                "declared": True,
            }
            decision = stages.p8_verdict(claim, bt, {}, False)
            return decision.verdict, decision.kill_reason, decision.metrics
        finally:
            P7.LEDGER = old_ledger


def run_part_a(seeds: int) -> dict:
    verdicts: Counter[str] = Counter()
    kill_reasons: Counter[str] = Counter()
    structural_kills = 0
    kills = 0

    for k in range(seeds):
        verdict, kill_reason, _metrics = _score_marginal_edge(k)
        verdicts[verdict] += 1
        if kill_reason:
            kill_reasons[kill_reason] += 1
        if verdict == "kill":
            kills += 1
            if kill_reason in STRUCTURAL_KILLS:
                structural_kills += 1

    denom = max(1, seeds)
    return {
        "seeds": seeds,
        "structural_kills": structural_kills,
        "kills": kills,
        "structural_kill_rate": structural_kills / denom,
        "kill_rate": kills / denom,
        "verdicts": dict(sorted(verdicts.items())),
        "kill_reasons": dict(sorted(kill_reasons.items())),
    }


def run_part_b(seeds: int) -> dict:
    verdicts: Counter[str] = Counter()
    kill_reasons: Counter[str] = Counter()
    supported = 0
    watch = 0
    clean_watch = 0

    for k in range(seeds):
        verdict, kill_reason, metrics = _score_mined_noise(k)
        verdicts[verdict] += 1
        if kill_reason:
            kill_reasons[kill_reason] += 1
        if verdict == "research-supported":
            supported += 1
        if verdict == "watch":
            watch += 1
            if not metrics.get("no_post_sample_data"):
                clean_watch += 1

    denom = max(1, seeds)
    return {
        "seeds": seeds,
        "supported": supported,
        "watch": watch,
        "clean_watch": clean_watch,
        "supported_rate": supported / denom,
        "watch_rate": watch / denom,
        "clean_watch_rate": clean_watch / denom,
        "verdicts": dict(sorted(verdicts.items())),
        "kill_reasons": dict(sorted(kill_reasons.items())),
    }


def main() -> None:
    try:
        seeds = int(sys.argv[1]) if len(sys.argv) > 1 else 60
    except ValueError as exc:
        raise SystemExit("usage: calibration_power_mining.py [positive_integer_seeds]") from exc
    if seeds <= 0:
        raise SystemExit("seeds must be a positive integer")

    print(f"[PEN-12] marginal-edge + mined-noise calibration (enforcing); seeds={seeds}")
    result = run_part_a(seeds)
    print("\nPart A: true marginal edge, IC=0.05, SD=0.01, T=1000 daily")
    print(f"  structural kills: {result['structural_kills']}/{seeds} = "
          f"{100 * result['structural_kill_rate']:.1f}%")
    print(f"  kills:            {result['kills']}/{seeds} = {100 * result['kill_rate']:.1f}%")
    print(f"  verdicts:         {result['verdicts']}")
    print(f"  kill reasons:     {result['kill_reasons']}")
    mined = run_part_b(seeds)
    print("\nPart B: best-of-500 mined zero-edge noise submitted as one external claim")
    print(f"  research-supported: {mined['supported']}/{seeds} = "
          f"{100 * mined['supported_rate']:.1f}%")
    print(f"  clean watch:        {mined['clean_watch']}/{seeds} = "
          f"{100 * mined['clean_watch_rate']:.1f}%")
    print(f"  watch (any):        {mined['watch']}/{seeds} = {100 * mined['watch_rate']:.1f}%")
    print(f"  verdicts:           {mined['verdicts']}")
    print(f"  kill reasons:       {mined['kill_reasons']}")
    # --- PEN-12 acceptance gate (enforcing) --------------------------------------------------
    # The DECLARED config floor (config.POWER["realistic_ic_floor"]) is frozen; these thresholds
    # are the spec's. A true marginal edge must not structurally kill above 20% (kill above 25%),
    # and best-of-K mined noise must never reach a survivor verdict (research-supported 0%,
    # clean-watch <= 10%). A breach is a real regression — fix the gate, never the floor.
    breaches = []
    if result["structural_kill_rate"] > 0.20:
        breaches.append(f"Part A structural-kill {100 * result['structural_kill_rate']:.1f}% > 20%")
    if result["kill_rate"] > 0.25:
        breaches.append(f"Part A kill {100 * result['kill_rate']:.1f}% > 25%")
    if mined["supported_rate"] > 0.0:
        breaches.append(f"Part B research-supported {100 * mined['supported_rate']:.1f}% > 0%")
    if mined["clean_watch_rate"] > 0.10:
        breaches.append(f"Part B clean-watch {100 * mined['clean_watch_rate']:.1f}% > 10%")
    # B-02: any-watch is the deflation-sensitive mined-noise metric; supported and clean-watch
    # can be structurally capped by holdout and post-sample evidence.
    if mined["watch_rate"] > 0.10:
        breaches.append(f"Part B any-watch {100 * mined['watch_rate']:.1f}% > 10%")
    if breaches:
        print("\nPEN-12 FAIL — calibration breached acceptance thresholds:")
        for b in breaches:
            print(f"  - {b}")
        raise SystemExit(1)
    print("\nPEN-12 PASS — marginal-edge false-kill and mined-noise pass rates within thresholds.")


if __name__ == "__main__":
    main()
